# Generated by Django 6.0.1 on 2026-02-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_comentarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
